### ISSUE TITLE
can you specify license in README?

### ISSUE THREAD

**Issue by rkawala** [CruGlobal/atlassian-hamcrest#3]
It would be great if you could indicate the license under which this library can be used. MIT? BSD? GPL? Apache? Thanks!

**Comment by mattdrees** [comment]
Yeah, good point. I'll see if I can figure out what the original was licensed under.

**Comment by mattdrees** [comment]
The original didn't specify a license. But I was able to contact Rich Wallace, and he said the Apache license would be fine. This is the license that Atlassian chose to use with their open-source tools, and although this happened years after the original atlassian-hamcrest lived and died, I think it's probably the closest thing I have to guide the original intent.

I'll update the readme.
